name: Trigger benchmark

on:
  push:
    branches:
      - 'main'

jobs:
  Trigger:
    name: Trigger benchmark
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.KHEPRI_BENCHMARK_REPO_ACCESS_TOKEN }}
          repository: rabbitmq/khepri-benchmark
          event-type: push-in-khepri
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
